[project]
authors = ["deepthought <deepthough@postech.ac.kr>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "ANARCI"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.8.*"
biopython = ">=1.83,<2"
hmmer = "3.3.2"
setuptools = ">=75.3.0,<76"
